### ISSUE TITLE
folder already exists when a plugin creates the folder

### ISSUE THREAD

**Issue by afmeva** [broccolijs/broccoli#357] opened 2018-03-14 20:10 UTC
I know that Broccoli intentionally does not have the options to either force or delete by default existing folders. But, how should one manage when the folder is created within the build process itself?

I'm using `broccoli-rollup` and I want to use a rollup plugin to handle `scss` imports directly inside the file. Besides some issues related to the extension filter(broccoli utils) and the fs.writeFile method, I managed to make it work (patching some stuff in the code) with the  `rollup-plugin-scss`. The thing is that the plugin creates the missing folder, in this case the `dist`folder so now broccoli is not ending the process because at this point it finds a folder already created.

**Comment by stefanpenner** [comment] 2018-11-29 03:13
It isn't entirely clear what the issue is, could a reproduction be provided?

**Comment by stefanpenner** [comment] 2019-05-20 15:02
Closing for now, will gladly reopen my above question can be answered.

**Closed** 2019-05-20 15:02 UTC
