### ISSUE TITLE
stop current build, when rebuild is triggered.

### ISSUE THREAD

**Issue by gabrielcsapo** [broccolijs/broccoli#407] opened 2019-05-21 16:36 UTC
When a funnel is being built, if a command to build again has been issued again, the funnel should stop its build and rebuild.

**Comment by thoov** [comment] 2019-05-21 22:14
@gabrielcsapo Could you create a small repo with steps to reproduce?

**Comment by thoov** [comment] 2019-05-28 06:07
Closing this issue as there hasn't been any movement on it for the last week. Feel free to reopen if you are able to create the reproduction steps.

**Comment by rwjblue** [comment] 2019-05-28 14:46
FWIW, this is a legit feature request and something that @stefanpenner and I have discussed and planned on doing for quite a while (roughly since he implemented the cancelation code for Broccoli 2.0).

**Comment by rwjblue** [comment] 2019-05-28 14:50
Steps to repro:

1) Have a large build pipeline that takes a few seconds
2) change a file (kicks off a rebuild)
3) change another file _during_ that rebuild


Expected result:

* Broccoli should stop calling any node's `.build` method immediately after step 3 (essentially short circuiting the build) and start over

Actual result:

* The build from step 2 completes then the build queued up in step 3 starts, therefore taking 2x the total time (time to complete two rebuilds vs time to do one full rebuild and whatever partial amount was previously completed)

**Comment by stefanpenner** [comment] 2019-05-28 20:31
> Broccoli should stop calling any node's .build method immediately after step 3 (essentially short circuiting the build) and start over


More specifically, it should continue the current build, and skip the next.

The code for this is actually largely implemented, but I believe requires the watcher be connected to the builder, to close the loop. Now that @oligriffiths and @thoov work landed, that should be quite easy to do.

cc @thoov maybe we can quickly look at that later today/tomorrow.

**Comment by gabrielcsapo** [comment] 2019-05-28 22:12
I have a working PR here https://github.com/broccolijs/broccoli/pull/408 that should do exactly what was talked about in this thread. Thanks for explaining @rwjblue and @stefanpenner

**Comment by oligriffiths** [comment] 2019-05-29 03:24
@gabrielcsapo thanks for the PR. I don’t think that gets us far enough. The Builder cancellation functionality needs updating first. Will work on a fix for this.

**Closed** 2020-03-17 19:25 UTC
